LIB	= Pz
SRCS=	McObject.cc McSub.cc MmObject.cc MmHeader.cc MvFunction.cc \
	McInit.cc McNull.cc McEther.cc McIPv6.cc McICMPv6.cc McRR.cc\
	McMIPv6.cc \
	McIPv4.cc McICMPv4.cc McNoNext.cc McUDP.cc McTCP.cc McARP.cc \
	PObject.cc PcObject.cc PlObject.cc PvObject.cc PvName.cc PvOctets.cc \
	ItPosition.cc WObject.cc RObject.cc PControl.cc \
	PvAction.cc PvAutoItem.cc PvIfName.cc \
	MmChecksum.cc MvArgCheck.cc DmObject.cc PrItem.cc\
	McAlgorithm.cc MfAlgorithm.cc PAlgorithm.cc McESP.cc McAH.cc MmData.cc

CXXFLAGS= -pipe -g -Wall -I./ -I$(Cm)

.include "bsd.lib.mk"
