#
# Copyright (C) IPv6 Promotion Council,
# NIPPON TELEGRAPH AND TELEPHONE CORPORATION (NTT),
# Yokogwa Electoric Corporation, YASKAWA INFORMATION SYSTEMS Corporation
# and NTT Advanced Technology Corporation(NTT-AT) All rights reserved.
# 
# Technology Corporation.
# 
# Redistribution and use of this software in source and binary forms, with 
# or without modification, are permitted provided that the following 
# conditions and disclaimer are agreed and accepted by the user:
# 
# 1. Redistributions of source code must retain the above copyright 
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
# notice, this list of conditions and the following disclaimer in the 
# documentation and/or other materials provided with the distribution.
# 
# 3. Neither the names of the copyrighters, the name of the project which 
# is related to this software (hereinafter referred to as "project") nor 
# the names of the contributors may be used to endorse or promote products 
# derived from this software without specific prior written permission.
# 
# 4. No merchantable use may be permitted without prior written 
# notification to the copyrighters. However, using this software for the 
# purpose of testing or evaluating any products including merchantable 
# products may be permitted without any notification to the copyrighters.
# 
# 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHTERS, THE PROJECT AND 
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING 
# BUT NOT LIMITED THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE, ARE DISCLAIMED.  IN NO EVENT SHALL THE 
# COPYRIGHTERS, THE PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT,STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE.
#
########################################################################

TITLE   = "Conformance Test for Home Agent"
PROFILE = "Conformance Test Specification:<BR>Mobility Support in IPv6<BR>Home Agent"
INDEX                   = ./INDEX
INDEX_PHASE2            = ./INDEX_PHASE2
INDEX_PHASE2_FINE_GRAIN = ./INDEX_PHASE2_FINE_GRAIN

clean:
	-rm -f	\
		INDEX				\
		INDEX_PHASE2			\
		INDEX_PHASE2_FINE_GRAIN		\
		index.html			\
		report.html			\
		summary.html			\
		[0-9]*.html			\
		*.dump				\
		*.log				\
		*.tmp				\
		*.bak				\
		ipsec_sa.pl			\
		config.pm			\
		config.def			\
		sequence.def			\
		ikesub.def			\
		pod2htmd*			\
		pod2htmi*			\
		*.rtadvd.conf			\
		local_haad_reply.def		\
		local_ra_deregistration.def	\
		local_ra_registration.def

INDEX: config.txt
	@(./configure.pl -i $(INDEX) ./config.txt)

check: INDEX
	$(AUTORUN) $(AROPT) -t -tiny $(INDEX)

document: INDEX
	$(AUTORUN) $(AROPT) -g -title=$(TITLE) $(INDEX)

document2: INDEX
	$(AUTORUN) $(AROPT) -G -title=$(TITLE) $(INDEX)

tahi: document
	-rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -title=$(TITLE) -dump2txt $(INDEX)

test: INDEX
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE) $(INDEX)

profile:
	@(./configure.pl -a -i $(INDEX) ./config.txt)
	$(AUTORUN) $(AROPT) -profile -nofooter -title=$(PROFILE) $(INDEX)


#
# for phase2
#
########################################################################

INDEX_PHASE2: config.txt
	@(./configure.pl -l 1 -i $(INDEX_PHASE2) ./config.txt)

document_ipv6ready_p2: INDEX_PHASE2
	$(AUTORUN) $(AROPT) -g -title=$(TITLE) $(INDEX_PHASE2)

ipv6ready_p2: INDEX_PHASE2
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE) $(INDEX_PHASE2)

profile_ipv6ready_p2:
	@(./configure.pl -a -l 1 -i $(INDEX_PHASE2) ./config.txt)
	$(AUTORUN) $(AROPT) -profile -nofooter -title=$(PROFILE) $(INDEX_PHASE2)


#
# for phase2, advanced function "Fine-Grain Selectors"
#
########################################################################

INDEX_PHASE2_FINE_GRAIN: config.txt
	@(./configure.pl -l 2 -i $(INDEX_PHASE2_FINE_GRAIN) ./config.txt)

document_ipv6ready_p2_fine_grain: INDEX_PHASE2_FINE_GRAIN
	$(AUTORUN) $(AROPT) -g -title=$(TITLE) $(INDEX_PHASE2_FINE_GRAIN)

ipv6ready_p2_fine_grain: INDEX_PHASE2_FINE_GRAIN
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE) $(INDEX_PHASE2_FINE_GRAIN)

profile_ipv6ready_p2_fine_grain:
	@(./configure.pl -l 2 -a -i $(INDEX_PHASE2_FINE_GRAIN) ./config.txt)
	$(AUTORUN) $(AROPT) -profile -nofooter -title=$(PROFILE) $(INDEX_PHASE2_FINE_GRAIN)


.include "../Makefile.inc"

# End of File
