#
# $Name: T_DHCPv6_Self_Test_P2_1_1_4 $
#
# Copyright (C) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009
# Yokogawa Electric Corporation.
# All rights reserved.
# 
# Redistribution and use of this software in source and binary
# forms, with or without modification, are permitted provided that
# the following conditions and disclaimer are agreed and accepted
# by the user:
# 
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with
#    the distribution.
# 
# 3. Neither the names of the copyrighters, the name of the project
#    which is related to this software (hereinafter referred to as
#    "project") nor the names of the contributors may be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
# 
# 4. No merchantable use may be permitted without prior written
#    notification to the copyrighters.
# 
# 5. The copyrighters, the project and the contributors may prohibit
#    the use of this software at any time.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHTERS, THE PROJECT AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING
# BUT NOT LIMITED THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE, ARE DISCLAIMED.  IN NO EVENT SHALL THE
# COPYRIGHTERS, THE PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# $TAHI: dhcpv6.p2/rfc3736/Makefile.test,v 1.5 2010/03/30 07:49:59 mario Exp $
#
################################################################

PERL    = /usr/bin/perl
POD2HTML= -$(PERL) -e 'use Pod::Html; pod2html("--noindex", @ARGV);'
RM      = /bin/rm

TITLE_CLIENT	= 'Section 7 : RFC3736 - Stateless DHCPv6 for DNS configuration for Client'
TITLE_SERVER	= 'Section 8 : RFC3736 - Stateless DHCPv6 for DNS configuration for Server'
TITLE_RELAY	= 'Section 9 : RFC3736 - Stateless DHCPv6 for DNS configuration for Relay agent'
TITLE_RR	= 'RFC3736 - Stateless DHCPv6 for DNS configuration for Requesting Router'
TITLE_DR	= 'RFC3736 - Stateless DHCPv6 for DNS configuration for Delegating Router'


INDEX_P2_CLIENT	= ./INDEX_p2_client
INDEX_P2_SERVER	= ./INDEX_p2_server
INDEX_P2_RELAY	= ./INDEX_p2_relay
INDEX_P2_RR	= ./INDEX_p2_requesting_router
INDEX_P2_DR	= ./INDEX_p2_delegating_router


#------------------------------#
# client                       #
#------------------------------#
document_ipv6ready_p2_client:
	$(AUTORUN) -profile $(INDEX_P2_CLIENT) -title=$(TITLE_CLIENT)

ipv6ready_p2_client: document_ipv6ready_p2_client
	/bin/rm -f DHCPv6_test_pkt.def index.html summary.html report.html
	chmod +x *.seq
	touch DHCPv6_test_pkt.def
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE_CLIENT) $(INDEX_P2_CLIENT)

#------------------------------#
# server                       #
#------------------------------#
document_ipv6ready_p2_server:
	$(AUTORUN) -profile $(INDEX_P2_SERVER) -title=$(TITLE_SERVER)

ipv6ready_p2_server: document_ipv6ready_p2_server
	/bin/rm -f DHCPv6_test_pkt.def index.html summary.html report.html
	chmod +x *.seq
	touch DHCPv6_test_pkt.def
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE_SERVER) $(INDEX_P2_SERVER)

#------------------------------#
# relay agent                  #
#------------------------------#
document_ipv6ready_p2_relay:
	$(AUTORUN) -profile $(INDEX_P2_RELAY) -title=$(TITLE_RELAY)

ipv6ready_p2_relay: document_ipv6ready_p2_relay
	/bin/rm -f DHCPv6_test_pkt.def index.html summary.html report.html
	chmod +x *.seq
	touch DHCPv6_test_pkt.def
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE_RELAY) $(INDEX_P2_RELAY)

#------------------------------#
# requesting router            #
#------------------------------#
document_ipv6ready_p2_requesting_router:
	$(AUTORUN) -profile -title=$(TITLE_RR) $(INDEX_P2_RR)

ipv6ready_p2_requesting_router: document_ipv6ready_p2_requesting_router
	/bin/rm -f DHCPv6_test_pkt.def index.html summary.html report.html
	chmod +x *.seq
	touch DHCPv6_test_pkt.def
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE_RR) $(INDEX_P2_RR)

#------------------------------#
# delegating router            #
#------------------------------#
document_ipv6ready_p2_delegating_router:
	$(AUTORUN) -profile -title=$(TITLE_DR) $(INDEX_P2_DR)

ipv6ready_p2_delegating_router: document_ipv6ready_p2_delegating_router
	/bin/rm -f DHCPv6_test_pkt.def index.html summary.html report.html
	chmod +x *.seq
	touch DHCPv6_test_pkt.def
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE_DR) $(INDEX_P2_DR)

clean:
	-$(RM) -f *.pcap *.dump *.log [0-9]*.html index.html report.html summary.html *.conf DHCPv6_test_pkt.def ztemp ztempdns *.tmp

.include "../Makefile.inc"

