#
# Copyright (C) IPv6 Promotion Council,
# NIPPON TELEGRAPH AND TELEPHONE CORPORATION (NTT),
# Yokogwa Electoric Corporation, YASKAWA INFORMATION SYSTEMS Corporation
# and NTT Advanced Technology Corporation(NTT-AT) All rights reserved.
# 
# Technology Corporation.
# 
# Redistribution and use of this software in source and binary forms, with 
# or without modification, are permitted provided that the following 
# conditions and disclaimer are agreed and accepted by the user:
# 
# 1. Redistributions of source code must retain the above copyright 
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
# notice, this list of conditions and the following disclaimer in the 
# documentation and/or other materials provided with the distribution.
# 
# 3. Neither the names of the copyrighters, the name of the project which 
# is related to this software (hereinafter referred to as "project") nor 
# the names of the contributors may be used to endorse or promote products 
# derived from this software without specific prior written permission.
# 
# 4. No merchantable use may be permitted without prior written 
# notification to the copyrighters. However, using this software for the 
# purpose of testing or evaluating any products including merchantable 
# products may be permitted without any notification to the copyrighters.
# 
# 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHTERS, THE PROJECT AND 
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING 
# BUT NOT LIMITED THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE, ARE DISCLAIMED.  IN NO EVENT SHALL THE 
# COPYRIGHTERS, THE PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT,STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE.
#
########################################################################

TITLE   = "Conformance Test for Mobile Router"
PROFILE = "Conformance Test Specification:<BR>Network Mobility (NEMO)<BR>Mobile Router"
INDEX                   = ./INDEX
INDEX_PHASE2            = ./INDEX.phase2
INDEX_PHASE2_FINE_GRAIN = ./INDEX.phase2.fine_grain
CONFIG = ./mip6_mn_config.pl

clean:
	-rm -f \
	index.html report.html summary.html [0-9]*.html analysis.html \
	*.dump *.log \
	mip6_mn_config.def \
	mip6_mn_nut_addr.def mip6_mn_cn0_addr.def mip6_mn_r2_addr.def \
	mip6_mn_sa.def ike.def ikesub.def \
	*.ini *.tmp

check:
	-echo "0" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -t -tiny $(INDEX)

document:
	$(AUTORUN) $(AROPT) -g -title=$(TITLE) $(INDEX)

document2:
	$(AUTORUN) $(AROPT) -G -title=$(TITLE) $(INDEX)

tahi: document
	-rm -f index.html summary.html report.html analysis.html
	-echo "0" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -title=$(TITLE) -dump2txt $(INDEX)

test:
	-echo "0" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE) $(INDEX)

profile:
	-echo "0" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -profile -nofooter -title=$(PROFILE) $(INDEX)


#
# for phase2
#
########################################################################

document_ipv6ready_p2:
	$(AUTORUN) $(AROPT) -g -title=$(TITLE) $(INDEX_PHASE2)

ipv6ready_p2:
	-echo "1" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE) $(INDEX_PHASE2)

profile_ipv6ready_p2:
	-echo "1" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -profile -nofooter -title=$(PROFILE) $(INDEX_PHASE2)


#
# for phase2, advanced function "Fine-Grain Selectors"
#
########################################################################

document_ipv6ready_p2_fine_grain:
	$(AUTORUN) $(AROPT) -g -title=$(TITLE) $(INDEX_PHASE2_FINE_GRAIN)

ipv6ready_p2_fine_grain:
	-echo "2" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -F -tiny -title=$(TITLE) $(INDEX_PHASE2_FINE_GRAIN)

profile_ipv6ready_p2_fine_grain:
	-echo "2" > logo.ini
	$(CONFIG)
	$(AUTORUN) $(AROPT) -profile -nofooter -title=$(PROFILE) $(INDEX_PHASE2_FINE_GRAIN)


.include "./mip6_mn_index.def"
.include "../Makefile.inc"

# End of File
