LIB       = Pflow
SRCS      = PflowAddrAlias.c            \
            PflowAnalyzeTime.c          \
            PflowEspHdr.c               \
            PflowEtherType.c            \
            PflowFragHdr.c              \
            PflowIcmp.c                 \
            PflowIcmpv6.c               \
            PflowIn6IsAddrLinklocal.c   \
            PflowIn6IsAddrMcGlobal.c    \
            PflowIn6IsAddrMcLinklocal.c \
            PflowIn6IsAddrMcSitelocal.c \
            PflowIn6IsAddrSitelocal.c   \
            PflowIn6IsAddrUnspecified.c \
            PflowIn6IsAddrV4mapped.c    \
            PflowIpDstAddr.c            \
            PflowIpSrcAddr.c            \
            PflowLoadPkt.c              \
            PflowMacDstAddr.c           \
            PflowMacSrcAddr.c           \
            PflowMakeHdr.c              \
            PflowMakeIpFlow.c           \
            PflowMakeLine.c             \
            PflowMakeMacFlow.c          \
            PflowNextHdr.c              \
            PflowPrintAddrTbl.c         \
            PflowPrintFtr.c             \
            PflowPrintInfo.c            \
            PflowPrintPkt.c             \
            PflowProtocol.c             \
            PflowReadDef.c              \
            PflowResolveAddr.c          \
            PflowSortAddr.c             \
            PflowSortMacAddr.c          \
            PflowTcp.c                  \
            PflowUdp.c                  \
            PflowUsage.c
CXXFLAGS += -I.

.include "bsd.lib.mk"
